dependencies:
#- name: btcd-kube
#  repository: http://jenkins-x-chartmuseum:8080
#  version: 0.0.60
- name: bitcoind-kube
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.56
- name: lnd-kube
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.58
