PipelineSecrets: {}
bitcoind-kube:
  configurationFile:
    bitcoin.conf: |-
      server=1
      zmqpubrawblock=tcp://0.0.0.0:28332
      zmqpubrawtx=tcp://0.0.0.0:28333
      txindex=1
      dbcache=3072Mi
  project:
    namespace: lightning-kube-mainnet
    network: mainnet
    networkSuffix: -mainnet
    storage: 275Gi
  resources:
    limits:
      cpu: 200m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 2048Mi
btcd-kube:
  project:
    namespace: lightning-kube-mainnet
    network: mainnet
    networkSuffix: -mainnet
    storage: 275Gi
  service:
    http:
      externalPort: 8333
      internalPort: 8333
    rpc:
      externalPort: 8334
      internalPort: 8334
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 35.225.224.89.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global: {}
lnd-kube:
  project:
    namespace: lightning-kube-mainnet
    network: mainnet
    networkSuffix: -mainnet
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 1024Mi
project:
  namespace: btcd-kube
  network: mainnet
  networkSuffix: -mainnet
prow: {}
